# Generated by Django 5.2.17 on 2026-09-24 06:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_alertlog_sent_at_alter_alertlog_status_and_more'),
        ('students', '0002_student_class_room_student_guardian_contact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['class_room', 'is_active'], name='students_st_class_r_6f92a6_idx'),
        ),
    ]
