# Generated by Django 5.2.17 on 2026-09-24 06:59

import django.db.models.deletion
from django.db import migrations, models


def populate_classrooms(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    for s in Student.objects.filter(class_room__isnull=False):
        s.classrooms.add(s.class_room)


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_alertlog_sent_at_alter_alertlog_status_and_more'),
        ('students', '0003_student_students_st_class_r_6f92a6_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classrooms',
            field=models.ManyToManyField(blank=True, related_name='students', to='attendance.classroom'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_students', to='attendance.classroom'),
        ),
        migrations.RunPython(populate_classrooms, migrations.RunPython.noop),
    ]
