# Generated by Django 5.2.17 on 2026-09-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_classrooms_alter_student_class_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='guardian_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Guardian Email'),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_phone',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Guardian Phone'),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_telegram_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Guardian Telegram ID'),
        ),
    ]
