# Generated by Django 5.2.17 on 2026-09-24 06:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('students', '0002_student_class_room_student_guardian_contact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertlog',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='alertlog',
            name='status',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='checked_in_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='ended_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='alertlog',
            index=models.Index(fields=['student', 'session', 'status'], name='attendance__student_473311_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['session', 'is_deleted'], name='attendance__session_73ecf8_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['session', 'status', 'is_deleted'], name='attendance__session_b53856_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['student', 'checked_in_at'], name='attendance__student_24a8ab_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['class_room', 'date'], name='attendance__class_r_7b513e_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['date', 'ended_at'], name='attendance__date_5ff320_idx'),
        ),
    ]
