# Generated by Django 5.2.17 on 2026-09-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_alertlog_sent_at_alter_alertlog_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='room',
            field=models.CharField(blank=True, default='', help_text='Physical room/lab identifier, e.g. Room 204 or Lab B', max_length=50),
        ),
        migrations.AddField(
            model_name='session',
            name='is_cancelled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['is_cancelled', 'date'], name='attendance__is_canc_f2fb3e_idx'),
        ),
    ]
