# Generated by Django 5.2.17 on 2026-09-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_classroom_room_session_is_cancelled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='co_teachers',
            field=models.ManyToManyField(blank=True, help_text='Assistant or co-teachers authorized to manage this classroom.', related_name='assistant_classrooms', to='attendance.teacher'),
        ),
        migrations.AddField(
            model_name='session',
            name='started_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when session was activated/started.', null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='method',
            field=models.CharField(choices=[('qr', 'QR Code'), ('face', 'Face Recognition'), ('manual', 'Manual'), ('system', 'System / Auto')], default='manual', max_length=10),
        ),
    ]
